config_nova_network_pubif: eth0
config_provision_demo: n
config_swift_install: n
config_neutron_metering_agent_install: y
config_nagios_install: n
config_lbaas_install: y
config_neutron_fwaas: y
config_nova_install: n
