---
- name: reload-systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart-sslocal
  service:
    name: sslocal
    state: restarted

- name: restart-privoxy
  service:
    name: sslocal
    state: restarted
