---
- name: reload-systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart-dhclient
  service:
    name: dhclient
    state: restarted

- name: restart-libvirtd
  service:
    name: libvirtd
    state: restarted

- name: restart-rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart-network
  service:
    name: network
    state: restarted
