docker_network_options: '--host=tcp://127.0.0.1:23456 --host=unix:///var/run/docker.sock'
k8s_bin_url: http://s3.amazonaws.com/k8s-bin-dev/k8s-bin-20160218-1.tar.gz

etcd_listen_client_urls: http://{{ ansible_eth0.ipv4.address }}:2379
