---
- hosts: all
  sudo: true
  vars:
    proxy_env:
      http_proxy: http://127.0.0.1:8118
      https_proxy: https://127.0.0.1:8118
  tasks:
    ###### install common package ######
    - name: check CentOS-Base.repo
      stat: path=/etc/yum.repos.d/CentOS-Base.repo.backup
      register: orig_centos_base_repo
    - name: backup CentOS-Base.repo
      command: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
      when: orig_centos_base_repo.stat.exists == False
    - name: download CentOS-Base.repo from 163
      get_url: url=http://mirrors.163.com/.help/CentOS7-Base-163.repo dest=/etc/yum.repos.d/CentOS-Base.repo
    - name: install epel-release
      yum:
        name: epel-release
        state: present
    - name: install common package
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - net-tools
        - python-pip
        - git

    ###### start shadowsocks sslcoal service(socks5 proxy) ######
    - name: install shadowsocks
      pip:
        name: shadowsocks
        version: 2.8.2
    - file: path=/etc/shadowsocks state=directory mode=0755
    - name: config shadowsocks
      copy: src=etc/shadowsocks/client.json dest=/etc/shadowsocks/client.json
    - name: install unit file for sslocal service
      copy: src=usr/lib/systemd/system/sslocal.service dest=/usr/lib/systemd/system/sslocal.service
      notify:
        - reload-systemd
    - name: reload-systemd
      sudo: yes
      command: systemctl daemon-reload
    - name: start sslocal service
      service: name=sslocal state=started enabled=yes

    ###### start privoxy service(socks5 proxy -> http proxy) ######
    - name: install privoxy
      yum:
        name: privoxy
        state: present
    - name: config privoxy
      copy: src=etc/privoxy/config dest=/etc/privoxy/config
    - name: start privoxy service
      service: name=privoxy state=started enabled=yes

    ###### init ######
    - name: generate h8s_deploy_env
      shell: echo -e "HOSTNAME='h8s-single'\nIF_NAME='eth0'\nIF_IP='{{ ansible_eth0.ipv4.address }}'\nKEYSTONE_ADMIN_PW='$(uuidgen)'\nKEYSTONE_DEMO_PW='$(uuidgen)'\nRBD_SECRET_UUID='$(uuidgen)'" > /root/h8s_deploy_env
      args:
        chdir: /root/
        creates: h8s_deploy_env
    # set ssh
    - file: path=/root/.ssh state=directory mode=0755
    - name: set ssh keypair
      copy: src=ssh/{{ item }} dest=/root/.ssh/
      with_items:
        - id_rsa
        - id_rsa.pub
        - config
    - file: path=/root/.ssh/id_rsa owner=root group=root mode=0400

    ###### clone devops ######
    # this is a private git repo, need add deploy key(example: deploy-for-dev-redadonly) in github with public keypair with "ssh/id_rsa.pub"
    - name: set deploy key for github
      copy: src=github/deploy.pem dest=/root/.ssh/deploy.pem
    - file: path=/root/.ssh/deploy.pem owner=root group=root mode=0400
    - git: repo=git@github.com:getdvm/devops.git dest=/root/devops version=master accept_hostkey=yes key_file=/root/.ssh/deploy.pem
      environment: "{{ proxy_env }}"

    ###### base setup ######
    - name: run 1_base_setup.sh
      shell: (sh ./1_base_setup.sh /root/h8s_deploy_env) && touch /root/1_base_setup.ok
      args:
        chdir: /root/devops/hypernetes-single-node/
        creates: /root/1_base_setup.ok
