---
###### install image service ######
- name: check image-service RPM
  stat: path=/root/imaged-0.5.0-1.el7.centos.x86_64.rpm
  register: imaged_rpm
- name: download image-service RPM
  when: imaged_rpm.stat.exists == False
  get_url: url="{{ item }}" dest=/root
  environment: "{{ proxy_env }}"
  with_items:
    - http://hyper-upload.s3.amazonaws.com/hyper-imaged-dev/qemu-hyper-2.4.1-3.el7.centos.x86_64.rpm
    - http://hyper-upload.s3.amazonaws.com/hyper-imaged-dev/imaged-0.5.0-1.el7.centos.x86_64.rpm
- name: install image-service
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - /root/qemu-hyper-2.4.1-3.el7.centos.x86_64.rpm
    - /root/imaged-0.5.0-1.el7.centos.x86_64.rpm

###### start image-service ######
- name: config imaged
  copy: src=etc/imaged/config dest=/etc/imaged/config
- name: start imaged
  service:
    name: imaged
    state: started
    enabled: yes
