---
- name: install dependency package
  environment: "{{ proxy_env }}"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-devel
    - device-mapper-devel
    - automake
    - autoconf
    - gcc
    - wget
    - time
    - git
    - gdb

- name: install ceph devel package
  environment: "{{ proxy_env }}"
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: ceph
  with_items:
    - librados2-devel
    - librbd1-devel


###### install image service ######
- name: check image-service RPM
  stat: path=/root/imaged-0.5.0-1.el7.centos.x86_64.rpm
  register: imaged_rpm
- name: download image-service RPM
  when: imaged_rpm.stat.exists == False
  get_url: url="{{ item }}" dest=/root
  environment: "{{ proxy_env }}"
  with_items:
    - http://hyper-upload.s3.amazonaws.com/hyper-imaged-dev/qemu-hyper-2.4.1-3.el7.centos.x86_64.rpm
    - http://hyper-upload.s3.amazonaws.com/hyper-imaged-dev/imaged-0.5.0-1.el7.centos.x86_64.rpm
- name: install image-service
  environment: "{{ proxy_env }}"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - /root/qemu-hyper-2.4.1-3.el7.centos.x86_64.rpm
    - /root/imaged-0.5.0-1.el7.centos.x86_64.rpm

###### start image-service ######
- name: config imaged
  copy: src=etc/imaged/config dest=/etc/imaged/config
- name: start imaged
  service:
    name: imaged
    state: started
    enabled: yes


###### clone and build image-service ######
- name: ensure dir $GOPATH/src/github.com/getdvm
  file:
    name: "{{ go_path }}/src/github.com/getdvm"
    state: directory
    mode: 0755

- name: check imaged repo
  shell: ls image-service/.git/config | wc -l
  register: imaged_exist
  args:
    chdir: "{{ go_path }}/src/github.com/getdvm"
- name: clone imaged
  when: imaged_exist.stdout == "0"
  environment: "{{ proxy_env }}"
  git:
    repo: git@github.com:getdvm/image-service.git
    dest: "{{ go_path }}/src/github.com/getdvm/image-service"
    version: master
    accept_hostkey: yes
    key_file: /root/.ssh/deploy.pem

- name: go get dependency
  environment: "{{ proxy_env }}"
  shell: |
    . $HOME/.bashrc
    go get "{{ item }}"
  with_items:
    - github.com/kardianos/govendor
    - github.com/eapache/go-resiliency/breaker
    - github.com/eapache/go-xerial-snappy
    - github.com/eapache/queue
    - github.com/pierrec/lz4
    - github.com/rcrowley/go-metrics

- name: clone libdocker
  environment: "{{ proxy_env }}"
  git:
    repo: git@github.com:getdvm/libdocker.git
    dest: "{{ go_path }}/src/github.com/getdvm/libdocker"
    version: master
    accept_hostkey: yes
    key_file: /root/.ssh/deploy.pem

- name: build imaged
  shell: |
    . $HOME/.bashrc
    ./update-libdocker.sh
    ./autogen.sh
    ./configure
    make
  args:
    chdir: "{{ go_path }}/src/github.com/getdvm/image-service"
    creates: imaged

- name: check imaged version
  shell: ./imagectl version
  args:
    chdir: "{{ go_path }}/src/github.com/getdvm/image-service"


#[to debug imaged]: sudo gdb --args ./imaged --nondaemon --log_dir=/var/log/imaged -v=4 --host=tcp://0.0.0.0:23451
- name: copy .gdbinit for gdb
  copy:
    src: gdb/gdbinit
    dest: /root/.gdbinit
