---

- name: create download dir for hyper rpm
  file:
    path: "{{ rpm_hyper }}"
    state: directory
    mode: 0755
- name: download hyper rpm
  get_url:
    url: "http://s3.amazonaws.com/hyper-install/{{ item.name }}"
    dest: "{{ rpm_hyper }}"
    checksum: "{{ item.checksum }}"
  with_items:
    - { name: "hyper-0.5-1.el7.centos.x86_64.rpm", checksum: "md5:416663986e507c69480d16ed09bf765a" }
    - { name: "hyperstart-0.5-1.el7.centos.x86_64.rpm", checksum: "md5:59d143aaa5c6216176e9a391a5d3b1aa" }
    - { name: "qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm", checksum: "md5:b142264e8409f4d0e08a8e51adc35b7d" }

- name: install hyper
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ rpm_hyper }}/hyper-0.5-1.el7.centos.x86_64.rpm"
    - "{{ rpm_hyper }}/hyperstart-0.5-1.el7.centos.x86_64.rpm"
    - "{{ rpm_hyper }}/qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm"

- name: install libvirt
  yum:
    name: libvirt
    state: present

- name: config hyper
  template:
    src: etc/hyper/config
    dest: /etc/hyper/config

- name: start libvirtd and hyperd service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - libvirtd
    - hyperd
