---
- name: check old installer for openstack
  shell: |
      (ps -ef | grep  "puppet.*packstack" | grep -v grep) && exit 1 || echo OK ;

- file:
    path: /root/deps
    state: directory
    mode: 0755

# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/3/html/Getting_Started_Guide/appe-Getting_Started_Guide-Removing_PackStack_Deployments.html
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Deploying_OpenStack_Proof_of_Concept_Environments/chap-Removing_Packstack_Deployments.html
- name: copy uninstall script
  copy: src={{ item }} dest=/root/ mode="0755"
  with_fileglob:
    - tools/*

# install packstack
- name: install openstack-packstack
  environment: "{{ proxy_env }}"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-packstack

- name: check packstack version
  shell: packstack --version | awk '{print $1, $2}'
  register: packstack_version
- debug:
    msg: "{{ packstack_version.stdout }}"
- fail:
    msg: "packstack version should be 'Liberty'"
  when: packstack_version.stdout != "packstack Liberty"

# install python support for redis(or yum install python-redis)
- name: install redis for python
  pip:
    name: redis

# install memcached service and patch systemd config for memcached
- name: install memcached
  yum:
    name: memcached
    state: present
- name: patch /usr/lib/systemd/system/memcached.service
  shell: grep "#MemoryDenyWriteExecute=" /usr/lib/systemd/system/memcached.service ||(sed -i 's/^MemoryDenyWriteExecute=/#MemoryDenyWriteExecute=/' /usr/lib/systemd/system/memcached.service; systemctl daemon-reload; systemctl restart memcached)


- name: install sshpass
  environment: "{{ proxy_env }}"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - sshpass

###### run install openstack ######
# Editing a PackStack Answer File: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/4/html/Getting_Started_Guide/Editing_a_PackStack_Answer_File.html
# ensure "mariadb-server" isn't installed before start packstack
# log :/var/tmp/packstack/latest/openstack-setup.log
###################################
#generate answer.txt
- name: generate answer.txt
  template:
    src: answer.txt
    dest: /root/deps/answer.txt
- name: run packstack if '/root/deps/packstack.ok' not exist
  environment: "{{ proxy_env }}"
  shell: |
    echo "===========================";
    env;
    echo "===========================";
    cp /root/deps/answer.txt /root/deps/answer.txt.bak
    echo "===========================";
    packstack --answer-file=/root/deps/answer.txt && touch /root/deps/packstack.ok
  args:
    chdir: /root
    creates: /root/deps/packstack.ok

- name: patch /usr/lib/systemd/system/neutron-server.service
  shell: grep 'TimeoutStartSec="infinity"' /usr/lib/systemd/system/neutron-server.service && (sed -i 's/^TimeoutStartSec="infinity"/TimeoutStartSec=0/' /usr/lib/systemd/system/neutron-server.service; systemctl daemon-reload; systemctl restart neutron-server) || echo neutron-server.service was patched



#install oslo.i18n(fix "ImportError: cannot import name _lazy")
- name: install oslo.i18n
  pip:
    name: oslo.i18n
    version: 3.4.0

#create ext_network
- name: add -x filemode to /root/keystonerc_admin
  file:
    path: /root/keystonerc_admin
    mode: 0700
- name: check ext_network
  shell: . /root/keystonerc_admin && neutron net-list | grep 'br\-ex' | wc -l
  register: ext_network
- debug: msg={{ ext_network.stdout }}

- name: create ext_network
  shell: . /root/keystonerc_admin && neutron net-create --router:external br-ex
  when: ext_network.stdout == "0"

#config neutron-server
- name: config neutron-server
  copy:
    src: etc/neutron.conf
    dest: /etc/neutron.conf

#install openstack-neutron-openvswitch and iptables
- name: install openstack-neutron-openvswitch
  environment: "{{ proxy_env }}"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-neutron-openvswitch

- name: start openvswitch service
  service:
    name: openvswitch
    state: started
    enabled: yes

- name: check openstack status
  shell: openstack-status

################################################################################################
# == Glance services ==
# openstack-glance-api:                   active
# openstack-glance-registry:              active
# == Keystone service ==
# openstack-keystone:                     inactive  (disabled on boot)
# == Horizon service ==
# openstack-dashboard:                    active
# == neutron services ==
# neutron-server:                         active
# neutron-dhcp-agent:                     active
# neutron-l3-agent:                       active
# neutron-metadata-agent:                 inactive  (disabled on boot)
# neutron-lbaas-agent:                    active
# neutron-lbaasv2-agent:                  inactive  (disabled on boot)
# neutron-openvswitch-agent:              active
# neutron-metering-agent:                 active
# == Cinder services ==
# openstack-cinder-api:                   active
# openstack-cinder-scheduler:             active
# openstack-cinder-volume:                active
# openstack-cinder-backup:                inactive  (disabled on boot)
# == Ceilometer services ==
# openstack-ceilometer-api:               active
# openstack-ceilometer-central:           active
# openstack-ceilometer-compute:           inactive  (disabled on boot)
# openstack-ceilometer-collector:         active
# openstack-ceilometer-alarm-notifier:    active
# openstack-ceilometer-alarm-evaluator:   active
# openstack-ceilometer-notification:      active
# == Support services ==
# mariadb:                                active
# libvirtd:                               active
# openvswitch:                            active
# dbus:                                   active
# target:                                 active
# rabbitmq-server:                        active
# memcached:                              active
# == Keystone users ==
# Warning keystonerc not sourced
################################################################################################
# openstack-ceilometer-alarm-evaluator.service    loaded active running   OpenStack ceilometer alarm evaluation service
# openstack-ceilometer-alarm-notifier.service     loaded active running   OpenStack ceilometer alarm notification service
# openstack-ceilometer-api.service                loaded active running   OpenStack ceilometer API service
# openstack-ceilometer-central.service            loaded active running   OpenStack ceilometer central agent
# openstack-ceilometer-collector.service          loaded active running   OpenStack ceilometer collection service
# openstack-ceilometer-notification.service       loaded active running   OpenStack ceilometer notification agent
# openstack-cinder-api.service                    loaded active running   OpenStack Cinder API Server
# openstack-cinder-scheduler.service              loaded active running   OpenStack Cinder Scheduler Server
# openstack-cinder-volume.service                 loaded active running   OpenStack Cinder Volume Server
# openstack-glance-api.service                    loaded active running   OpenStack Image Service (code-named Glance) API server
# openstack-glance-registry.service               loaded active running   OpenStack Image Service (code-named Glance) Registry server
# openstack-losetup.service                       loaded active exited    Setup cinder-volume loop device
################################################################################################
