---
- file:
    path: /root/deps
    state: directory
    mode: 0755

- name: copy uninstall script
  copy: src={{ item }} dest=/root/ mode="0755"
  with_fileglob:
    - tools/*

#generate my_answer.txt
- name: generate my_answer.txt
  template:
    src: my_answer.txt
    dest: /root/deps/my_answer.txt
  tags:
   - generate-my_answer.txt

# install packstack
- name: install openstack-packstack
  yum:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env }}"
  with_items:
    - openstack-packstack
    - python-openstackclient
    - memcached
    - httpd
    - haproxy
    - erlang
    - ruby

- name: check env for install openstack
  shell: |
      (ps -ef | grep  "puppet.*packstack" | grep -v grep) || echo OK ;

###### run install openstack ######
# ensure "mariadb-server" isn't installed before start packstack
# log :/var/tmp/packstack/latest/openstack-setup.log
###################################
- name: run packstack if '/root/deps/packstack.ok' not exist
  shell: |
    env;
    ((rpm -qa | grep mariadb-server) && yum remove -y mariadb-server || echo mariadb-server not installed) && packstack --answer-file=/root/deps/my_answer.txt && touch /root/deps/packstack.ok
  args:
    chdir: /root
    creates: /root/deps/packstack.ok
  environment: "{{ proxy_env }}"

- name: install sshpass
  yum:
    name: sshpass
    state: present
  environment: "{{ proxy_env }}"

#install oslo.i18n(fix "ImportError: cannot import name _lazy")
- name: install oslo.i18n
  pip:
    name: oslo.i18n
    version: 3.4.0

#create ext_network
- name: add -x filemode to /root/keystonerc_admin
  file:
    path: /root/keystonerc_admin
    mode: 0700
- name: check ext_network
  shell: . /root/keystonerc_admin && neutron net-list | grep 'br\-ex' | wc -l
  register: ext_network
- debug: msg={{ ext_network.stdout }}

- name: create ext_network
  shell: . /root/keystonerc_admin && neutron net-create --router:external br-ex
  when: ext_network.stdout == "0"

#config neutron-server
- name: config neutron-server
  copy:
    src: etc/neutron.conf
    dest: /etc/neutron.conf

#install openstack-neutron-openvswitch and iptables
- name: install openstack-neutron-openvswitch
  yum:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env }}"
  with_items:
    - openstack-neutron-openvswitch

- name: start openvswitch service
  service:
    name: openvswitch
    state: started
    enabled: yes

- name: check openstack status
  shell: openstack-status

################################################################################################
# == Glance services ==
# openstack-glance-api:                   active
# openstack-glance-registry:              active
# == Keystone service ==
# openstack-keystone:                     inactive  (disabled on boot)
# == Horizon service ==
# openstack-dashboard:                    active
# == neutron services ==
# neutron-server:                         active
# neutron-dhcp-agent:                     active
# neutron-l3-agent:                       active
# neutron-metadata-agent:                 inactive  (disabled on boot)
# neutron-lbaas-agent:                    active
# neutron-lbaasv2-agent:                  inactive  (disabled on boot)
# neutron-openvswitch-agent:              active
# neutron-metering-agent:                 active
# == Cinder services ==
# openstack-cinder-api:                   active
# openstack-cinder-scheduler:             active
# openstack-cinder-volume:                active
# openstack-cinder-backup:                inactive  (disabled on boot)
# == Ceilometer services ==
# openstack-ceilometer-api:               active
# openstack-ceilometer-central:           active
# openstack-ceilometer-compute:           inactive  (disabled on boot)
# openstack-ceilometer-collector:         active
# openstack-ceilometer-alarm-notifier:    active
# openstack-ceilometer-alarm-evaluator:   active
# openstack-ceilometer-notification:      active
# == Support services ==
# mariadb:                                active
# libvirtd:                               active
# openvswitch:                            active
# dbus:                                   active
# target:                                 active
# rabbitmq-server:                        active
# memcached:                              active
# == Keystone users ==
# Warning keystonerc not sourced
################################################################################################
# openstack-ceilometer-alarm-evaluator.service    loaded active running   OpenStack ceilometer alarm evaluation service
# openstack-ceilometer-alarm-notifier.service     loaded active running   OpenStack ceilometer alarm notification service
# openstack-ceilometer-api.service                loaded active running   OpenStack ceilometer API service
# openstack-ceilometer-central.service            loaded active running   OpenStack ceilometer central agent
# openstack-ceilometer-collector.service          loaded active running   OpenStack ceilometer collection service
# openstack-ceilometer-notification.service       loaded active running   OpenStack ceilometer notification agent
# openstack-cinder-api.service                    loaded active running   OpenStack Cinder API Server
# openstack-cinder-scheduler.service              loaded active running   OpenStack Cinder Scheduler Server
# openstack-cinder-volume.service                 loaded active running   OpenStack Cinder Volume Server
# openstack-glance-api.service                    loaded active running   OpenStack Image Service (code-named Glance) API server
# openstack-glance-registry.service               loaded active running   OpenStack Image Service (code-named Glance) Registry server
# openstack-losetup.service                       loaded active exited    Setup cinder-volume loop device
################################################################################################
