---

- name: ensure dir /root/deps/docker
  file: path=/root/deps/docker state=directory mode=0755


# patch for "shim error: docker-runc not installed on system"
- name: ensure /usr/libexec/docker dir
  shell: mkdir -p /usr/libexec/docker
  args:
    creates: /usr/libexec/docker
- name: create soft link for 'docker-runc-current'
  shell: ln -s docker-runc-current docker-runc
  args:
    chdir:  /usr/libexec/docker
    creates:  /usr/libexec/docker/docker-runc

- name: create soft link for 'docker-current'
  shell: ln -s docker-current docker
  args:
    chdir:  /bin
    creates:  /bin/docker


- name: Download docker-1.12.6 with check (sha256)
  get_url:
    url: http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    dest: /root/deps/docker/docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    #checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  environment: "{{ proxy_env }}"
- name: Download docker-client-1.12.6 with check (sha256)
  get_url:
    url: http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    dest: /root/deps/docker/docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    #checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  environment: "{{ proxy_env }}"
- name: Download docker-common-1.12.6 with check (sha256)
  get_url:
    url: http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    dest: /root/deps/docker/docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    #checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  environment: "{{ proxy_env }}"

- name: install docker
  shell: yum install -y *.rpm
  environment: "{{ proxy_env }}"
  args:
    chdir: /root/deps/docker
    creates: /bin/docker-current


# - name: install docker
#   yum:
#     name: "http://mirror.centos.org/centos/7/extras/x86_64/Packages/{{ item }}"
#     state: present
#   environment: "{{ proxy_env }}"
#   with_items:
#     - docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
#     - docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
#     - docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm


- name: copy script for docker0
  copy: src={{ item }} dest=/root/ mode="0755"
  with_fileglob:
    - tools/*

# delete default docker0 (192.168.121.1)
- name: delete default docker0
  shell: /root/teardown-default-docker0.sh


# - name: add user to docker group
#   user: name=vagrant comment="default user" group=docker

- name: start docker service
  service: name=docker state=started enabled=yes

- name: ensure dir /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: config for docker service
  template:
    src: etc/systemd/system/docker.service.d/dockeropt.conf
    dest: /etc/systemd/system/docker.service.d/dockeropt.conf
  register: docker_systemd_config
  notify:
    - reload-systemd
    - restart-docker

- name: ensure systemd is reloaded if dockeropt.conf has changed
  when: docker_systemd_config.changed
  shell: |
    systemctl daemon-reload
    systemctl restart docker


# ansible docker module required
- name: install docker-py
  pip:
    name: docker-py
    state: present
    version: 1.10.6
