---

- name: ensure dir /root/deps/docker
  file: path=/root/deps/docker state=directory mode=0755


# patch for "shim error: docker-runc not installed on system"
- name: ensure /usr/libexec/docker dir
  shell: mkdir -p /usr/libexec/docker
  args:
    creates: /usr/libexec/docker
- name: create soft link for 'docker-runc-current'
  shell: ln -s docker-runc-current docker-runc
  args:
    chdir:  /usr/libexec/docker
    creates:  /usr/libexec/docker/docker-runc

- name: create soft link for 'docker-current'
  shell: ln -s docker-current docker
  args:
    chdir:  /bin
    creates:  /bin/docker

- name: Download docker-1.12.6
  environment: "{{ proxy_env }}"
  get_url:
    url: "http://mirror.centos.org/centos/7/extras/x86_64/Packages/{{ item.name }}"
    dest: /root/deps/docker
    checksum: "{{ item.checksum }}"
  with_items:
    - { name: "docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm", checksum: "md5:74eddccc69c1f184614bb109d91d84f5" }
    - { name: "docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm", checksum: "md5:0d739d7c9f5fa0f1c746b34999823766" }
    - { name: "docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm", checksum: "md5:6ad2a0d3aae91e7d984aeb993dc64a34" }

- name: install docker
  environment: "{{ proxy_env }}"
  yum:
    name: "/root/deps/docker/{{ item }}"
    state: present
  with_items:
    - "docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm"
    - "docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm"
    - "docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm"

# - name: install docker
#   environment: "{{ proxy_env }}"
#   shell: yum install -y *.rpm
#   args:
#     chdir: /root/deps/docker
#     creates: /bin/docker-current


- name: copy script for docker0
  copy: src={{ item }} dest=/root/ mode="0755"
  with_fileglob:
    - tools/*

# delete default docker0 (192.168.121.1)
- name: delete default docker0
  shell: /root/teardown-default-docker0.sh


# - name: add user to docker group
#   user: name=vagrant comment="default user" group=docker

- name: start docker service
  service: name=docker state=started enabled=yes

- name: ensure dir /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: config for docker service
  template:
    src: etc/systemd/system/docker.service.d/dockeropt.conf
    dest: /etc/systemd/system/docker.service.d/dockeropt.conf
  register: docker_systemd_config
  notify:
    - reload-systemd
    - restart-docker

- name: ensure systemd is reloaded if dockeropt.conf has changed
  when: docker_systemd_config.changed
  shell: |
    systemctl daemon-reload
    systemctl restart docker


# ansible docker module required
- name: install docker-py
  pip:
    name: docker-py
    state: present
    version: 1.10.6
