---
###### start docker daemon ######
- name: add docker yum repo
  copy: src=etc/yum.repos.d/docker-main.repo dest=/etc/yum.repos.d/docker-main.repo

# - name: install dependency package for docker
#   yum:
#     name: "{{ item }}"
#     state: present
#   environment: "{{ proxy_env }}"
#   with_items:
#     - libseccomp
#     - policycoreutils-python

- name: ensure dir /root/deps/docker
  file: path=/root/deps/docker state=directory mode=0755

- name: download docker
  shell: wget -c -P /root/deps/docker -O "{{ item }}" "http://mirror.centos.org/centos/7/extras/x86_64/Packages/{{ item }}"
  environment: "{{ proxy_env }}"
  with_items:
    - docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    - docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    - docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    # - container-selinux-2.12-2.gite7096ce.el7.noarch.rpm
    # - oci-register-machine-0-3.11.gitdd0daef.el7.x86_64.rpm
    # - oci-systemd-hook-0.1.7-2.git2788078.el7.x86_64.rpm
    # - skopeo-containers-0.1.19-1.el7.x86_64.rpm

- name: install docker
  yum:
    name: "/root/deps/docker/{{ item }}"
    state: present
  with_items:
    - docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    - docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm
    - docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm

- name: copy script for docker0
  copy: src={{ item }} dest=/root/ mode="0755"
  with_fileglob:
    - tools/*

# delete default docker0 (192.168.121.1)
- name: delete default docker0
  shell: /root/teardown-default-docker0.sh


# - name: add user to docker group
#   user: name=vagrant comment="default user" group=docker

- name: start docker service
  service: name=docker state=started enabled=yes

- name: ensure dir /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: config for docker service
  copy: src=etc/systemd/system/docker.service.d/dockeropt.conf dest=/etc/systemd/system/docker.service.d/dockeropt.conf
  register: docker_systemd_config
  notify:
    - reload-systemd
    - restart-docker

- name: ensure systemd is reloaded if dockeropt.conf has changed
  when: docker_systemd_config.changed
  shell: |
    systemctl daemon-reload
    systemctl restart docker

# patch for "shim error: docker-runc not installed on system"
- name: create soft link for 'docker-runc-current'
  shell: ln -s docker-runc-current docker-runc
  args:
    chdir:  /usr/libexec/docker
    creates:  /usr/libexec/docker/docker-runc

- name: create soft link for 'docker-current'
  shell: ln -s docker-current docker
  args:
    chdir:  /bin
    creates:  /bin/docker


# ansible docker module required
- name: install docker-py
  pip:
    name: docker-py
    state: present
    version: 1.10.6
