---

- name: ensure dir /root/deps/docker
  file: path=/root/deps/docker state=directory mode=0755


# patch for "shim error: docker-runc not installed on system"
- name: ensure /usr/libexec/docker dir
  shell: mkdir -p /usr/libexec/docker
  args:
    creates: /usr/libexec/docker
- name: create soft link for 'docker-runc-current'
  shell: ln -s docker-runc-current docker-runc
  args:
    chdir:  /usr/libexec/docker
    creates:  /usr/libexec/docker/docker-runc

- name: create soft link for 'docker-current'
  shell: ln -s docker-current docker
  args:
    chdir:  /bin
    creates:  /bin/docker

- name: check /root/deps/docker/checksum.md5
  shell: ls /root/deps/docker/checksum.md5 2>/dev/null | wc -l
  register: docker_rpm_exist
- name: Download docker-1.12.6
  when: docker_rpm_exist.stdout == "0"
  environment: "{{ proxy_env }}"
  get_url:
    url: "http://mirror.centos.org/centos/7/extras/x86_64/Packages/{{ item.name }}"
    dest: /root/deps/docker
    checksum: "{{ item.checksum }}"
  with_items:
    - { name: "docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm", checksum: "md5:74eddccc69c1f184614bb109d91d84f5" }
    - { name: "docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm", checksum: "md5:0d739d7c9f5fa0f1c746b34999823766" }
    - { name: "docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm", checksum: "md5:6ad2a0d3aae91e7d984aeb993dc64a34" }

- name: generate dokcer rpm md5
  shell: md5sum docker-* > checksum.md5
  args:
    chdir: /root/deps/docker
    creates: checksum.md5

- name: check docker installed
  shell: which docker 2>/dev/null | wc -l
  register: docker_installed
- name: install docker
  when: docker_installed.stdout == "0"
  environment: "{{ proxy_env }}"
  yum:
    name: "/root/deps/docker/{{ item }}"
    state: present
  with_items:
    - "docker-common-1.12.6-28.git1398f24.el7.centos.x86_64.rpm"
    - "docker-client-1.12.6-28.git1398f24.el7.centos.x86_64.rpm"
    - "docker-1.12.6-28.git1398f24.el7.centos.x86_64.rpm"

- name: copy script for docker0
  copy: src={{ item }} dest=/root/ mode="0755"
  with_fileglob:
    - tools/*

# delete default docker0 (192.168.121.1)
- name: delete default docker0
  shell: /root/teardown-default-docker0.sh


# - name: add user to docker group
#   user: name=vagrant comment="default user" group=docker

- name: start docker service
  service: name=docker state=started enabled=yes

- name: ensure dir /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: config for docker service
  template:
    src: etc/systemd/system/docker.service.d/dockeropt.conf
    dest: /etc/systemd/system/docker.service.d/dockeropt.conf
  register: docker_systemd_config
  notify:
    - reload-systemd
    - restart-docker

- name: ensure systemd is reloaded if dockeropt.conf has changed
  when: docker_systemd_config.changed
  shell: |
    systemctl daemon-reload
    systemctl restart docker

# uninstall urllib3 when python2-urllib3 not installed
- name: check python2-urllib3
  shell: rpm -qa | grep -E "(python2-urllib3|python-urllib3)" | wc -l
  register: python2_urllib3_installed
- name: solve conflict between urllib3 and python2-urllib3
  environment: "{{ proxy_env }}"
  when: python2_urllib3_installed.stdout == "0"
  pip:
    name: urllib3
    state: absent

- name: install python-urllib3
  yum:
    name: python-urllib3
    state: present

# ansible docker module required(uninstall docker-py first)
- name: install docker for python
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-py
