---
###### start docker daemon ######
- name: add docker yum repo
  copy: src=etc/yum.repos.d/docker-main.repo dest=/etc/yum.repos.d/docker-main.repo
- name: install docker
  yum:
    name: docker-engine
    state: present

- name: add user to docker group
  user: name=vagrant comment="default user" group=docker

- name: start docker service
  service: name=docker state=started enabled=yes

- name: ensure dir /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: config for docker service
  copy: src=etc/systemd/system/docker.service.d/dockeropt.conf dest=/etc/systemd/system/docker.service.d/dockeropt.conf
  register: docker_systemd_config
  notify:
    - reload-systemd
    - restart-docker

- name: ensure systemd is reloaded if dockeropt.conf has changed
  when: docker_systemd_config.changed
  shell: |
    systemctl daemon-reload
    systemctl restart docker

# ansible docker module required
- name: install docker-py
  pip:
    name: docker-py
    state: present
