---
- name: solve ssh slow
  copy: src=etc/ssh/sshd_config dest=/etc/ssh/sshd_config
  register: ssh_config
- name: restart sshd if sshd_config has changed
  when: ssh_config.changed
  shell: service sshd restart

- name: check CentOS-Base.repo
  stat: path=/etc/yum.repos.d/CentOS-Base.repo.backup
  register: orig_centos_base_repo
- name: backup CentOS-Base.repo
  command: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
  when: orig_centos_base_repo.stat.exists == False
- name: download CentOS-Base.repo from 163
  get_url: url=http://mirrors.163.com/.help/CentOS7-Base-163.repo dest=/etc/yum.repos.d/CentOS-Base.repo
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install common package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - net-tools
    - python-pip
    - libvirt
    - git
    - jq
    - iptables
    - iptables-services

- name: upgrade pip self
  shell: pip install --upgrade pip

# - name: uninstall urllib3 via pip
#   pip:
#     name: urllib3
#     state: absent
- name: install python-urllib3
  yum:
    name=python-urllib3
    state=present

###### start shadowsocks sslcoal service(socks5 proxy) ######
#shadowsocks need restart first_time
- name: install shadowsocks
  pip:
    name: shadowsocks
    version: 2.8.2
- file: path=/etc/shadowsocks state=directory mode=0755
- name: config shadowsocks
  template:
    src: etc/shadowsocks/client.json
    dest: /etc/shadowsocks/client.json
  notify:
    - restart-sslocal
- name: install unit file for sslocal service
  copy: src=usr/lib/systemd/system/sslocal.service dest=/usr/lib/systemd/system/sslocal.service
  notify:
    - reload-systemd
    - restart-sslocal
- name: reload-systemd
  command: systemctl daemon-reload
- name: start sslocal service
  service: name=sslocal state=restarted enabled=yes

###### start privoxy service(socks5 proxy -> http proxy) ######
#privoxy need restart first_time
- name: install privoxy
  yum:
    name: privoxy
    state: present
- name: config privoxy
  copy: src=etc/privoxy/config dest=/etc/privoxy/config
  notify:
    - restart-privoxy
- name: start privoxy service
  service: name=privoxy state=restarted enabled=yes


#disable firewalld
- name: disalbe firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: start iptables service
  service:
    name: iptables
    state: started
    enabled: yes

#check iptables
- name: check iptables
  shell: iptables -F && iptables -X

#disable selinux
- name: disable selinux
  selinux: state=disabled

#generate sysctl.conf
- name: generate /etc/sysctl.conf
  copy:
    src: etc/sysctl.conf
    dest: /etc/sysctl.conf
  tags:
    - generate-etc_sysctl_conf
- name: load bridge module
  command: modprobe bridge
- name: check sysctl
  command: sysctl -p

#generate limits.conf
- name: generate limits.conf
  copy:
    src: etc/security/limits.conf
    dest: /etc/security/limits.conf
  tags:
    - generate-etc_security_limits_conf
